### PR TITLE
Redefine `be` to be equivalent to `equal` for non-objects.

### PR DESCRIPTION
**Pull request by FeepingCreature**
Makes `text.should.be("foo")` work.

### CODE REVIEW

**Comment by FeepingCreature** [comment]
ping @linkrope

**Comment by FeepingCreature** [comment]
Comparison of other fluent assert libraries:

 - https://fluentassertions.com/nullabletypes/ : no reference comparisons
 - https://www.npmjs.com/package/fluent-assert : no reference comparisons
 - https://github.com/csparpa/fluentcheck : no reference comparisons
 - https://joel-costigliola.github.io/assertj/index.html : unusable documentation (can't find out)
 - https://github.com/evolutional/Chamois : no reference comparison

**Comment by belka-ew** [comment]
https://www.npmjs.com/package/fluent-assert ist höchstwahrscheinlich tot. Siehe [chai](https://www.chaijs.com/api/bdd/#method_equal) und [jest/expect](https://jestjs.io/docs/en/using-matchers)

- In `chai` ist `be` nur ein "Hilfsverb", um lesbare Chains zu schreiben
- Jest hat nur `toBeTruthy`, `toBeNull` u.Ä. (auf den ersten Blick wie die C#-Version)

**Comment by FeepingCreature** [comment]
closed: https://github.com/funkwerk/dshould/pull/5 is the only pr

**Pull request closed without merging**
